# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Produce a quantile number using Rcpp.
#' @description Produce the quantile of order q of a numeric vector.
#' @param x a numeric vector
#' @param q the order of the quantile
#' @return the quantile of order q of vector x
#' @import Rcpp
#' @examples
#' \dontrun{
#' x<-rcauchy(5,0,1)
#' quantile(x,0.5)
#' }
#' @useDynLib SA23204189
#' @export
quantile0 <- function(x, q) {
    .Call('_SA23204189_quantile0', PACKAGE = 'SA23204189', x, q)
}

#' @title Predict the positional parameter of a Cauchy distribution using Rcpp.
#' @description Predict the positional parameter of a Cauchy distribution using Rcpp.
#' @param x the sorted i.i.d Cauchy variables (NumericVector)
#' @param a the method (1 or 2) (int)
#' @return the point estimation of the positional parameter
#' @examples
#' \dontrun{
#' x<-rcauchy(50,0,1)
#' Cauchy_paraest_mu(x,1)
#' }
#' @useDynLib SA23204189
#' @export
Cauchy_paraest_mu <- function(x, a) {
    .Call('_SA23204189_Cauchy_paraest_mu', PACKAGE = 'SA23204189', x, a)
}

#' @title Predict the scale parameter of a Cauchy distribution using Rcpp.
#' @description Predict the scale parameter of a Cauchy distribution using Rcpp.
#' @param x the sorted i.i.d Cauchy variables (NumericVector)
#' @param b the method (1, 2 or 3) (int)
#' @return the point estimation of the scale parameter
#' @examples
#' \dontrun{
#' x<-rcauchy(50,0,1)
#' Cauchy_paraest_lambda(x,1)
#' }
#' @useDynLib SA23204189
#' @export
Cauchy_paraest_lambda <- function(x, b) {
    .Call('_SA23204189_Cauchy_paraest_lambda', PACKAGE = 'SA23204189', x, b)
}

